name: llm_chat_local
description: Local LLM Chat app (LM Studio) with streaming, Hive, Riverpod, Material 3
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.3.6

  # HTTP
  http: ^0.13.6

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14

  # UI
  flutter_material_symbols: ^0.0.1
  flutter_slidable: ^2.0.0
  uuid: ^4.5.1
  google_fonts: ^4.0.4
  flutter_animate: ^4.5.0
  rive: ^0.13.0

  flutter_markdown: ^0.7.7+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/
