import 'package:hive/hive.dart';

// Removed codegen part directive since manual adapter is used.

@HiveType(typeId: 2)
class ChatSession extends HiveObject {
  @HiveField(0)
  String id;

  @HiveField(1)
  String title; // autogenerated by first assistant message

  @HiveField(2)
  DateTime createdAt;

  @HiveField(3)
  DateTime updatedAt;

  ChatSession({
    required this.id,
    required this.title,
    DateTime? createdAt,
    DateTime? updatedAt,
  })  : createdAt = createdAt ?? DateTime.now(),
        updatedAt = updatedAt ?? DateTime.now();
}

/// Manual adapter for ChatSession (no codegen needed).
class ChatSessionAdapter extends TypeAdapter<ChatSession> {
  @override
  final typeId = 2;

  @override
  ChatSession read(BinaryReader reader) {
    final id = reader.readString();
    final title = reader.readString();
    final createdAt = DateTime.fromMillisecondsSinceEpoch(reader.readInt());
    final updatedAt = DateTime.fromMillisecondsSinceEpoch(reader.readInt());
    return ChatSession(id: id, title: title, createdAt: createdAt, updatedAt: updatedAt);
  }

  @override
  void write(BinaryWriter writer, ChatSession obj) {
    writer.writeString(obj.id);
    writer.writeString(obj.title);
    writer.writeInt(obj.createdAt.millisecondsSinceEpoch);
    writer.writeInt(obj.updatedAt.millisecondsSinceEpoch);
  }
}
